// Generates responsive AVIF + WebP versions of every photo, plus a tiny blurred placeholder,
// and writes their metadata to src/data/photos.gen.ts. Requires ffmpeg/ffprobe on PATH.
//   node scripts/optimize-images.mjs
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SRC = path.join(ROOT, 'public', 'photos')
const OUT = path.join(SRC, 'opt')
const STEPS = [800, 1400]

fs.mkdirSync(OUT, { recursive: true })
const ff = (...args) => execFileSync('ffmpeg', ['-y', '-v', 'error', ...args])
const meta = {}

for (const file of fs.readdirSync(SRC).filter(f => f.endsWith('.jpg')).sort()) {
  const name = file.replace(/\.jpg$/, '')
  const input = path.join(SRC, file)
  const [w, h] = execFileSync('ffprobe', ['-v', 'error', '-show_entries', 'stream=width,height', '-of', 'csv=p=0', input]).toString().trim().split(',').map(Number)
  const widths = [...new Set([...STEPS.filter(s => s < w), Math.min(w, 2000)])]
  for (const width of widths) {
    const scale = `scale=${width}:-2:flags=lanczos`
    const avif = path.join(OUT, `${name}-${width}.avif`)
    const webp = path.join(OUT, `${name}-${width}.webp`)
    if (!fs.existsSync(avif)) ff('-i', input, '-vf', scale, '-c:v', 'libaom-av1', '-still-picture', '1', '-cpu-used', '5', '-crf', '23', '-pix_fmt', 'yuv420p10le', avif)
    if (!fs.existsSync(webp)) ff('-i', input, '-vf', scale, '-c:v', 'libwebp', '-quality', '85', webp)
  }
  const lqip = execFileSync('ffmpeg', ['-v', 'error', '-i', input, '-vf', 'scale=20:-2', '-c:v', 'libwebp', '-quality', '40', '-f', 'webp', '-'])
  meta[name] = { w, h, widths, lqip: `data:image/webp;base64,${lqip.toString('base64')}` }
  process.stdout.write(`${name} `)
}

const body = `// Generated by scripts/optimize-images.mjs — do not edit by hand.
export interface PhotoMeta { w: number; h: number; widths: number[]; lqip: string }
export const PHOTOS: Record<string, PhotoMeta> = ${JSON.stringify(meta, null, 2)}
`
fs.writeFileSync(path.join(ROOT, 'src', 'data', 'photos.gen.ts'), body)
const bytes = dir => fs.readdirSync(dir).reduce((s, f) => s + fs.statSync(path.join(dir, f)).size, 0)
console.log(`\n${Object.keys(meta).length} photos → ${fs.readdirSync(OUT).length} files, ${(bytes(OUT) / 1e6).toFixed(1)} MB (originals ${(bytes(SRC) / 1e6).toFixed(1)} MB)`)
