// Reads the pixel size of every photo in public/photos and writes src/data/photoSizes.ts, so layouts can show each
// photo at its own proportions without jumping while images load. Run again after adding photos (needs ffprobe).
//   node scripts/photo-sizes.mjs
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const DIR = path.join(ROOT, 'public', 'photos')
const sizes = {}
for (const file of fs.readdirSync(DIR).filter((f) => f.endsWith('.jpg')).sort()) {
  const out = execFileSync('ffprobe', ['-v', 'error', '-show_entries', 'stream=width,height', '-of', 'csv=p=0', path.join(DIR, file)])
  sizes[file.replace(/\.jpg$/, '')] = out.toString().trim().split(',').map(Number)
}
const body = `// Generated by scripts/photo-sizes.mjs. Run it again after adding photos.
export const PHOTO_SIZES: Record<string, [number, number]> = ${JSON.stringify(sizes, null, 2).replace(/\[\n\s+(\d+),\n\s+(\d+)\n\s+\]/g, '[$1, $2]')}
`
fs.writeFileSync(path.join(ROOT, 'src', 'data', 'photoSizes.ts'), body)
console.log(`${Object.keys(sizes).length} photos`)
