// Generated by scripts/optimize-images.mjs — do not edit by hand.
export interface PhotoMeta { w: number; h: number; widths: number[]; lqip: string }
export const PHOTOS: Record<string, PhotoMeta> = {
  "angelina-1": {
    "w": 1600,
    "h": 900,
    "widths": [
      800,
      1400,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoUAAwAPu1iqU2ppaOiMAgBMB2JYgCdABLOdn3byx2gAAD+FJ75l3SAh+XuU+awBrr+JWZs4vD+IOLkK/aeWox5pdPRIy7FzkeCeW+9P4hrsAbWdVaR3FAA"
  },
  "angelina-2": {
    "w": 1600,
    "h": 901,
    "widths": [
      800,
      1400,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoUAAwAPu1iqU2ppaQiMAgBMB2JZACdABenkILAHvSSgAD9HKVbtk67JqI9jm76g1qAMXovuMu/sKdM+H4ZAz5j+gzcvOIDHRA4REMVvMq8yEXc3X2knAAA"
  },
  "angelina-3": {
    "w": 1600,
    "h": 1067,
    "widths": [
      800,
      1400,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACQAwCdASoUAA4APu1iqU2ppaQiMAgBMB2JYwAAM4VhI9jzAYBAAP5xu4td7/uNaqbz/Blc3plMnNfiVSJO+gJufcjKpcBBKQ7VgKG90mIar0sqxtwAAAAA"
  },
  "bride-1": {
    "w": 1600,
    "h": 900,
    "widths": [
      800,
      1400,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQAwCdASoUAAwAPu1iqU2ppaOiMAgBMB2JZQCw7BikRWB3Ru8jw4AA/ulHinfJHPPTZw1oSx68fYHunWXjvC5fVmtrx0ipneYDSVE2tTllLj8tYTwr2ROuUAVsieYIg7MX/WwfuwZPjFsxXgA="
  },
  "bride-2": {
    "w": 1600,
    "h": 900,
    "widths": [
      800,
      1400,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABQBACdASoUAAwAPu1iqU2ppaOiMAgBMB2JYwCdAdwA3ZBMkvJp6T7dlU0AAP7p9mJGG6X471GonEhXT6iQ6nKUgw+lhWarVn11dhtWucM9M+Qdgn1aUnhwMBev0QyH7Hsf0SAMP47xvJs/nqumQ5FC5/tv1ojHwjMxQjvPE1gAAA=="
  },
  "bride-group": {
    "w": 2000,
    "h": 1126,
    "widths": [
      800,
      1400,
      2000
    ],
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwBACdASoUAAwAPu1iqU2ppaOiMAgBMB2JaACdMoRwACK3XhJKDKxxQM39A8eAAOJ+zp9TveoztbtHCgOCHvhnEmW5EZbg5jskIHWoFUgPgvL9jx3HcViKnwFCgMZwzz1De4M0SS05Me61r+d0ehntu0oYmHBPhmFBeu9p4QEHyngatwurAAAA"
  },
  "fiori-1": {
    "w": 900,
    "h": 1600,
    "widths": [
      800,
      900
    ],
    "lqip": "data:image/webp;base64,UklGRvwAAABXRUJQVlA4IPAAAABQBgCdASoUACQAPu1uqlEppqOiqrgKATAdiWgAx+Qij0+OdnAy0rtVZkJqOcynFJbOMSJ4mDEOr0Y6IAD+3rXgk2HHyjYxeB5WeVXinxN1HyDia/it9sWjV7VYYR5RRp+UTt9hbGU3UOYgnw5rCOPHnUJqwccicnwpc/TeMj/5i7T24viJ4EN2IeZaB8zZM6UF1p3TnAjFgTiz2RGWbH2MVzhTYx5Q6WUCXDcujeglyLXnEQ6CsO29JWRqA49IOU8W5gJL9k0VjE/GminnXgXOy8Qt9DvsPcg0C4LBXHDMuqw9vHldFwFsSav8YkcAAAA="
  },
  "fiori-2": {
    "w": 1600,
    "h": 900,
    "widths": [
      800,
      1400,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBACdASoUAAwAPu1iqU2ppaOiMAgBMB2JQBdgMYxcsymRIFXQ5NtD8AAA/fPYiJoP619O1pIp+EZleKqlTV1V4nQa91MJnUL530oL/LqQAvBytnMw5UJQRq4SaW82DqCaennYkPFaJu+3QQpAHUQQGSS8gwO6U4m34RoXQCXXULgAAAA="
  },
  "fiori-3": {
    "w": 1600,
    "h": 900,
    "widths": [
      800,
      1400,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBACdASoUAAwAPu1iqU2ppaOiMAgBMB2JZACAAAk9IsM3g1pqgNFFPoAA/pEq2MXOk1aE6INgAPSb6luRvSteAktCIbzOwUpi5xFWzIvImamWziPD2ZymSBAJYp2fqshXuqxRglirb+m+t/otQydtfVnOIkU2oTmJbq/7AIDCJY2sgAAAAA=="
  },
  "fiori-4": {
    "w": 2000,
    "h": 1126,
    "widths": [
      800,
      1400,
      2000
    ],
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAwCdASoUAAwAPu1iqU2ppaOiMAgBMB2JYwAAP2+XFFaw0F62wK4AAP7MSVwcJdP0CaFFGDhmAgj6DvWF6/WkF2vOO1MNEbviJl5r6CZvk72bdW60QRaf/fS1VSDuIt4BtHcr67J3JbnwCuLPYJrlNjQAAA=="
  },
  "kayshawn-portrait": {
    "w": 1400,
    "h": 1400,
    "widths": [
      800,
      1400
    ],
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADwAwCdASoUABQAPu1cq04ppKQiMBgMATAdiWYAwNwQ7+u1dlR1w+AAAP7zfnyr4WyvlmwifY9/Mi00jirl1TH0s+A3a1yPKkTSRSylr+Hn8Q8Wg2eCYusoWZRYJ2m4lqO/5NbN9oQ2RxREjotTAZbv7qF3u+J2zQAAAA=="
  },
  "lolita-1": {
    "w": 900,
    "h": 1600,
    "widths": [
      800,
      900
    ],
    "lqip": "data:image/webp;base64,UklGRhQBAABXRUJQVlA4IAgBAABwBgCdASoUACQAPu1orFCppaQiqqgBMB2JZQDLbavW1NowK+Jns4lZBXDhLTaCyB+kxYp+/P0e61pnIXAA/u6T7nOlHIx4Qz0iERQ9swaxhGtbUJLFTBBLPw4ZBo3LSZXmmw1c04qX/MCSI4ntmBDSwGRFcPZG6SixTU78R9zA7f+8szeNNcTuBFVHcc6vaRll8DUSz7u8lWYsvqguLFJVx6GG256O978GpOkgFcLqCuniY4weE9/g1zU87hHSFzzf9E9UFUySfQAuPosoEtTuLpotx2Q18xhzdH3UF6938tQAZzNxYmeRsFS0KSDGApHaUTPydgp6sZOziIT88QP9b4JA1daQAAA="
  },
  "lolita-2": {
    "w": 900,
    "h": 1600,
    "widths": [
      800,
      900
    ],
    "lqip": "data:image/webp;base64,UklGRv4AAABXRUJQVlA4IPIAAAAwBwCdASoUACQAPu1urVCppqQiqqgBMB2JZQC9eWVYA+zgucD0z5MJlXd7GZ4ajIgSCyr119en+Q9vW+MttPCpMAAA/MjrY8fVhRQnB2Ig3vbkzlSdn0ia0fsczcXFynDD7rSVSjH6+aJSsrM2R8HAspuiFm1ZqEaAQH+hS68fbmlhDQLVtg0CD8YfjIUS6Xs0p+SKYwPiUH5OwObn5eBV82ERrHy95auGCMom66ABMXk7Qbx9d2DFHjJ+BzTxl+ib3mPwFeCOxvdewzQb+mjKBsOB7sAXwnptKo02nbRA6j0bi8TLTmY6hQN6yThyt3AAAA=="
  },
  "lolita-3": {
    "w": 900,
    "h": 1600,
    "widths": [
      800,
      900
    ],
    "lqip": "data:image/webp;base64,UklGRvIAAABXRUJQVlA4IOYAAACwBgCdASoUACQAPu1srVCppiQiqqgBMB2JZQDA4AolkIm3MvSh6flMVbWPyfcsQlQyLCNLbmPMQl2ab6LIMAD+4uroJ2wo/T868gX/R0dXruX0H/+pVqKgqT2VBi1N7K0uoPZrCj+GVyk119NwehVT4mpqx45TTtxK4hkUM6ae1iq0qZRMk1rDwCJCVj2uxh2uBUfkUfm7VRY8TvlFRF3CHDPklEyx9lE1soVoVd4S1H7kkjjcTHpWWgfd/neaDjQ0PoGoIdIUxktn/gz8Gz7MOEDRRzIH1HiUjVUoRJPgEKPWrVwAAA=="
  },
  "officer-1": {
    "w": 1600,
    "h": 900,
    "widths": [
      800,
      1400,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAwCdASoUAAwAPu1iqU2ppaOiMAgBMB2JZwDGfCG51xqMdAae/AAAAP69tCZWhjUJYJydSZGdtLM7vzf2eHRHngACUenTswtolpECxaaMHUvgL3MrAskHIM5iQyORPnxUSJSE/igW9kNm1EgAAA=="
  },
  "officer-4": {
    "w": 2000,
    "h": 1126,
    "widths": [
      800,
      1400,
      2000
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACQAwCdASoUAAwAPu1iqU2ppaOiMAgBMB2JZwAAQwSWJrUwCUAAAP5OBXRIdZH0Dj4aD76XwryhVmgyT4Qt/j8eMcqW5D7iT7hAh4krqoFjQAAA"
  },
  "officer-5": {
    "w": 900,
    "h": 1600,
    "widths": [
      800,
      900
    ],
    "lqip": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAADwBQCdASoUACQAPu1qq1CppaOiqqgBMB2JZQDDdbJAbSHsZwdIx07XIyoTKcVyi/PIvlhoBpGTAAD+gz2W+iYrtiLyYPBpdDInZpMV8caDjhAFvMWrHssZ3Y7l9Zl9495J6FQ69DSLU/iVMR9h0LKpHmPsTkqo+BY19foOTk/DVWLRmM+lJJ60N7VHHlFIdz4sr4d82U8x8a8TsctXfdThCx954FFYZG56Rn4HqY/hhMX6XQ9t7mLxH0jSFJEc4quZmSOCIzOrn5cnwWSAAA=="
  },
  "persaes-1": {
    "w": 900,
    "h": 1600,
    "widths": [
      800,
      900
    ],
    "lqip": "data:image/webp;base64,UklGRuAAAABXRUJQVlA4INQAAAAwBgCdASoUACQAPu1qrVCppaQipWzJMB2JZQDO8AgCOV5nXdiCAgFWVtACvWy1Ec1hLV0ALtn1GdpoAP71cxEfQa4qFBj79ht7RLd/bPcwHnRTANS+0+5BdLEk9ecAfaSMu3OIX8w40ZuAAOHo9AynQYFMbPiRFk9CEUyEd7yh1/XURP7vvS4ZWhp7Z7Z4CVBQAw1INmNssemtQ1NR/AK5FDk3Dlt48TkXIRlwnasmEhsZnIPtD+AnhEXgu87jFLbAgVsHwP3xnuinjsy847qAE1qAAA=="
  },
  "persaes-2": {
    "w": 900,
    "h": 1600,
    "widths": [
      800,
      900
    ],
    "lqip": "data:image/webp;base64,UklGRuoAAABXRUJQVlA4IN4AAACQBgCdASoUACQAPu1us1KppiSipWmZMB2JZwDKACMrdjQP38JLUb3oNconLJh06c678noKHHwW9Yphft4AAP7ypQCXccUlQgWxrC91yRISw58DRE56a52sRdpiZl4NBo6jSb8+C5GSKWxNFtimRQc3JHr8e05LbX6wKJYxc5WZwZTRz6otIeGyyLY/sQvX93eyKhY27yw5Z1BcIahOifigx5wZXdWFYn1y9a4Vob3T7HT7VnaQBK1yG/VZjD/R0IE+SF7nrKjzymQO+GZi94qitLTZL68ebxqh8Z2AAAA="
  },
  "purple-2": {
    "w": 900,
    "h": 1600,
    "widths": [
      800,
      900
    ],
    "lqip": "data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAABwBgCdASoUACQAPulepk2pJSOiMBqtUSAdCWMA0BgT6fT/3fhpvJhlwQf63n3Br73AXsLDDBTKd4nWKCAA/qhKmAVRBKc6WNi7WmIBLVo7ixZRoS2NgCTQP49bZWOTpW8J4he0lhkc4kLC1yuR/aDyUEup2mHlSDfAkeLDimZbm9+Y99laMkp70a0iOsZX50vaVNQKbe0PcNjNup/di+QUCLonHzSk2k/eBIrHJw1Aslb4NFyehBgAAAA="
  },
  "purple-3": {
    "w": 900,
    "h": 1600,
    "widths": [
      800,
      900
    ],
    "lqip": "data:image/webp;base64,UklGRhYBAABXRUJQVlA4IAoBAADQBgCdASoUACQAPu1oqVAppiOiqqoBMB2JQBiBJAh8szraHfcaR3xMPPmGN/kODfOycxu6O/eghaOdu/sCh0AA3mX0SLnBoCO076Hab7l3cL+4JeJix1pEoz5e6UlYM5DIAf1AGBGIANLK8m2GNUcNWR7utoc9awokf1eVlgsV6Ik68+lnSvtSXDKPa1fcgSn9ujfOLycpftSMB7nbEQ7d9TMCSci3/CphP9HYSwUPAunWKqaH9Wv0ndBoHhwULmQgvmPjtBR1iNZ06G0L9jzdtWSZp3XKHax2ja18+wkTNu7mFGf6QM/O1NkemQpioKtYtHQhDQacBCylzDsst3f7iYpg5/zUsAAAAA=="
  },
  "sparks-1": {
    "w": 1013,
    "h": 1800,
    "widths": [
      800,
      1013
    ],
    "lqip": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4IMQAAABwBgCdASoUACQAPu1qrVCppaQiqqgBMB2JZwDJB3JCUO7ODActbOVqXLySttH9I59Cq71VrVZDCW1z1wAA/tp5fqITuRUP9nLPidDPVEvc8rtysfEuYRCskX4A2lz+XkkWpsB9/Kwwy91gG4s4ac4bWCNd8iQSNT6onXVDLuNlEyckpIb83Jg5ANfB18Fo9zPEoesnIHs1g8kK5MwyCdYRne0WkHHubQV6m7oW4bhr8WzmOxg8PJhu5jAvurFzWGqt34AA"
  },
  "sparks-2": {
    "w": 1600,
    "h": 900,
    "widths": [
      800,
      1400,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoUAAwAPu1iqU2ppaOiMAgBMB2JaQDImCIdvHC8Hpcg/RDTAAAA/s2JvYsbHiz36w/c+2XHNglG+HkZlBtBGC562rLYNfXCnqsG8OJ9WEmrIpJVfTUAAA=="
  },
  "sparks-3": {
    "w": 2000,
    "h": 1126,
    "widths": [
      800,
      1400,
      2000
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQBACdASoUAAwAPu1iqk2ppaQiMAgBMB2JZwAAV999clB4QpD32LQAAAD3uTxl//sy0Emu7VlsrGE2d7bL6mP7POrWmopvSphEFutiytocUf9dmHMP0AAA"
  }
}
